/* Generated by Nim Compiler v1.9.1 */
/* Compiled for: Linux, i386, clang */
/* Command for C compiler:
   /usr/bin/clang-15 -c -w -ferror-limit=3 --target=wasm32-unknown-unknown-wasm -I/usr/include -flto -fvisibility=hidden -nostdlib -fdata-sections -ffunction-sections -DPRINTF_DISABLE_SUPPORT_FLOAT=1 -DPRINTF_DISABLE_SUPPORT_LONG_LONG=1 -DPRINTF_DISABLE_SUPPORT_PTRDIFF_T=1 -Os  -fPIC  -I'/root/.choosenim/toolchains/nim-#devel/lib' -I/root/wasmrt -o /root/wasmrt/nimcache/@m..@s.choosenim@stoolchains@snim-@hdevel@slib@ssystem@sexceptions.nim.c.o /root/wasmrt/nimcache/@m..@s.choosenim@stoolchains@snim-@hdevel@slib@ssystem@sexceptions.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_OverflowDefect__2PORNhst6IrjIwxgQkd4EA tyObject_OverflowDefect__2PORNhst6IrjIwxgQkd4EA;
typedef struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A;
typedef struct tyObject_ArithmeticDefect__LOkrIROjKUTubovxKzZX9cg tyObject_ArithmeticDefect__LOkrIROjKUTubovxKzZX9cg;
typedef struct tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct tyObject_IndexDefect__W7zFbor8bJ1meM16OWPdYg tyObject_IndexDefect__W7zFbor8bJ1meM16OWPdYg;
typedef struct tyObject_RangeDefect__MWJ9c9a6Gdq9bdIqtL2BKU9amg tyObject_RangeDefect__MWJ9c9a6Gdq9bdIqtL2BKU9amg;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct TNimTypeV2 {
void* destructor;
NI size;
NI16 align;
NI16 depth;
NU32* display;
void* traceImpl;
void* typeInfoV1;
NI flags;
};
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A {
NI rc;
};
struct RootObj {
TNimTypeV2* m_type;
};
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
Exception* up;
};
struct tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA {
  Exception Sup;
};
struct tyObject_ArithmeticDefect__LOkrIROjKUTubovxKzZX9cg {
  tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA Sup;
};
struct tyObject_OverflowDefect__2PORNhst6IrjIwxgQkd4EA {
  tyObject_ArithmeticDefect__LOkrIROjKUTubovxKzZX9cg Sup;
};
struct tyObject_IndexDefect__W7zFbor8bJ1meM16OWPdYg {
  tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA Sup;
};
struct tyObject_RangeDefect__MWJ9c9a6Gdq9bdIqtL2BKU9amg {
  tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA Sup;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_3723)(tyObject_OverflowDefect__2PORNhst6IrjIwxgQkd4EA* dest__0SVougbgzTwtS5BtPjXzjQ);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p__YLyUZk8Vki03tNo3UlpTrw);
static N_INLINE(NI, minuspercent___system_790)(NI x__nhqJNug5PDvy9ah8vc6uJ5Q, NI y__LJLJ0MGnpTb2U2nvMvG6MQ);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p__9avvNwjq1NdQwdCBwEYwA9bw);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_13)(NimStringV2* dest__C2JKGPCNdWKCPrsQvNywTQ);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_45)(tySequence__uB9b75OUPRENsBAu4AnoePA* dest__OvUJ7i3R9aE9as9bgGZONrFOA);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_3469)(tyObject_IndexDefect__W7zFbor8bJ1meM16OWPdYg* dest__0SVougbgzTwtS5BtPjXzjQ_2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_3437)(tyObject_RangeDefect__MWJ9c9a6Gdq9bdIqtL2BKU9amg* dest__0SVougbgzTwtS5BtPjXzjQ_3);
N_LIB_PRIVATE TNimTypeV2 NTIv2__2PORNhst6IrjIwxgQkd4EA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__W7zFbor8bJ1meM16OWPdYg_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__MWJ9c9a6Gdq9bdIqtL2BKU9amg_;
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_3[5] = {3701606400, 1285336064, 3079805440, 3911917824, 4086380032};
N_LIB_PRIVATE TNimTypeV2 NTIv2__2PORNhst6IrjIwxgQkd4EA_ = {.destructor = (void*)eqdestroy___system_3723, .size = sizeof(tyObject_OverflowDefect__2PORNhst6IrjIwxgQkd4EA), .align = (NI16) NIM_ALIGNOF(tyObject_OverflowDefect__2PORNhst6IrjIwxgQkd4EA), .depth = 4, .display = TM__TzI3paKQY09cLjc9cmCvur3A_3, .traceImpl = (void*)NIM_NIL, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_4[4] = {3701606400, 1285336064, 3079805440, 3167055360};
N_LIB_PRIVATE TNimTypeV2 NTIv2__W7zFbor8bJ1meM16OWPdYg_ = {.destructor = (void*)eqdestroy___system_3469, .size = sizeof(tyObject_IndexDefect__W7zFbor8bJ1meM16OWPdYg), .align = (NI16) NIM_ALIGNOF(tyObject_IndexDefect__W7zFbor8bJ1meM16OWPdYg), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_4, .traceImpl = (void*)NIM_NIL, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_5[4] = {3701606400, 1285336064, 3079805440, 1652553472};
N_LIB_PRIVATE TNimTypeV2 NTIv2__MWJ9c9a6Gdq9bdIqtL2BKU9amg_ = {.destructor = (void*)eqdestroy___system_3437, .size = sizeof(tyObject_RangeDefect__MWJ9c9a6Gdq9bdIqtL2BKU9amg), .align = (NI16) NIM_ALIGNOF(tyObject_RangeDefect__MWJ9c9a6Gdq9bdIqtL2BKU9amg), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_5, .traceImpl = (void*)NIM_NIL, .flags = 0};
static N_INLINE(NI, minuspercent___system_790)(NI x__nhqJNug5PDvy9ah8vc6uJ5Q, NI y__LJLJ0MGnpTb2U2nvMvG6MQ) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x__nhqJNug5PDvy9ah8vc6uJ5Q))) - (NU32)(((NU) (y__LJLJ0MGnpTb2U2nvMvG6MQ))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p__YLyUZk8Vki03tNo3UlpTrw) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	{
		tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* cell;
		NI T5_;
		if (!!((p__YLyUZk8Vki03tNo3UlpTrw == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_790(((NI) (ptrdiff_t) (p__YLyUZk8Vki03tNo3UlpTrw)), ((NI)4));
		cell = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_));
		{
			if (!((NI)((*cell).rc & ((NI)-8)) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
		LA8_: ;
		{
			NI TM__TzI3paKQY09cLjc9cmCvur3A_2;
			if (nimSubInt((*cell).rc, ((NI)8), &TM__TzI3paKQY09cLjc9cmCvur3A_2)) { raiseOverflow(); goto BeforeRet_;
			};
			(*cell).rc = (NI)(TM__TzI3paKQY09cLjc9cmCvur3A_2);
		}
		LA6_: ;
	}
	LA3_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_3723)(tyObject_OverflowDefect__2PORNhst6IrjIwxgQkd4EA* dest__0SVougbgzTwtS5BtPjXzjQ) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest__0SVougbgzTwtS5BtPjXzjQ).Sup.Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest__0SVougbgzTwtS5BtPjXzjQ).Sup.Sup.Sup.parent);
	}
	LA4_: ;
	eqdestroy___stdZassertions_13((&(*dest__0SVougbgzTwtS5BtPjXzjQ).Sup.Sup.Sup.message));
	eqdestroy___stdZassertions_45((&(*dest__0SVougbgzTwtS5BtPjXzjQ).Sup.Sup.Sup.trace));
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLast((*dest__0SVougbgzTwtS5BtPjXzjQ).Sup.Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest__0SVougbgzTwtS5BtPjXzjQ).Sup.Sup.Sup.up);
	}
	LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_3469)(tyObject_IndexDefect__W7zFbor8bJ1meM16OWPdYg* dest__0SVougbgzTwtS5BtPjXzjQ_2) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest__0SVougbgzTwtS5BtPjXzjQ_2).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest__0SVougbgzTwtS5BtPjXzjQ_2).Sup.Sup.parent);
	}
	LA4_: ;
	eqdestroy___stdZassertions_13((&(*dest__0SVougbgzTwtS5BtPjXzjQ_2).Sup.Sup.message));
	eqdestroy___stdZassertions_45((&(*dest__0SVougbgzTwtS5BtPjXzjQ_2).Sup.Sup.trace));
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLast((*dest__0SVougbgzTwtS5BtPjXzjQ_2).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest__0SVougbgzTwtS5BtPjXzjQ_2).Sup.Sup.up);
	}
	LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_3437)(tyObject_RangeDefect__MWJ9c9a6Gdq9bdIqtL2BKU9amg* dest__0SVougbgzTwtS5BtPjXzjQ_3) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest__0SVougbgzTwtS5BtPjXzjQ_3).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest__0SVougbgzTwtS5BtPjXzjQ_3).Sup.Sup.parent);
	}
	LA4_: ;
	eqdestroy___stdZassertions_13((&(*dest__0SVougbgzTwtS5BtPjXzjQ_3).Sup.Sup.message));
	eqdestroy___stdZassertions_45((&(*dest__0SVougbgzTwtS5BtPjXzjQ_3).Sup.Sup.trace));
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLast((*dest__0SVougbgzTwtS5BtPjXzjQ_3).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest__0SVougbgzTwtS5BtPjXzjQ_3).Sup.Sup.up);
	}
	LA9_: ;
}
