/* Generated by Nim Compiler v1.9.1 */
/* Compiled for: Linux, i386, clang */
/* Command for C compiler:
   /usr/bin/clang-15 -c -w -ferror-limit=3 --target=wasm32-unknown-unknown-wasm -I/usr/include -flto -fvisibility=hidden -nostdlib -fdata-sections -ffunction-sections -DPRINTF_DISABLE_SUPPORT_FLOAT=1 -DPRINTF_DISABLE_SUPPORT_LONG_LONG=1 -DPRINTF_DISABLE_SUPPORT_PTRDIFF_T=1 -Os  -fPIC  -I'/root/.choosenim/toolchains/nim-#devel/lib' -I/root/wasmrt -o /root/wasmrt/nimcache/@m..@s.choosenim@stoolchains@snim-@hdevel@slib@ssystem@srepr_v2.nim.c.o /root/wasmrt/nimcache/@m..@s.choosenim@stoolchains@snim-@hdevel@slib@ssystem@srepr_v2.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_Region__rcaGGUGHuXUOkC68lX2yPA tyObject_Region__rcaGGUGHuXUOkC68lX2yPA;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content* p;
};
struct tyObject_Region__rcaGGUGHuXUOkC68lX2yPA {
tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* offset;
NU32 capacity;
NU32 length;
};


#ifndef tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content_PP
#define tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content_PP
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content { NI cap; NU8 data[SEQ_DECL_SIZE];};
#endif

      N_LIB_PRIVATE N_NIMCALL(void, reprObject__nimwasm_304)(NimStringV2* res__Ts4Qs0N3SWIpMcs766LXNg, tyObject_Region__rcaGGUGHuXUOkC68lX2yPA x__DBOUjt6X9bDPwP3S5jEmWYA);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s__S65jkNxJ72wMzHX9bQ0it8w, NIM_CHAR c__q53woDK9bF1K5bAKmsVpSkA);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s__qL2AkrAohOvo9bZZC15G6TA, NI addlen__uGPPC8Yor9a9avOoki7IG3AQ);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, appendString)(NimStringV2* dest__Ws6Yi19bfxrbjCy9a9brzRV7A, NimStringV2 src__369aqaoei6FUsRf9cDAsKQ2g);
static N_INLINE(void, copyMem__system_1751)(void* dest__fJYjxXM6yYjbZ9agQpPnNNA, void* source__Y6ZnHEKiVLswf16AMGuQUA, NI size__YLlwRG7Z9bTiXmiSwU9cUHeA);
static N_INLINE(void, nimCopyMem)(void* dest__HMDJtGX4ficduS9cTUiey0w, void* source__xDZEU1SRcEBuZ8mtbKQBhQ, NI size__9b8g0WMA1h1RvMwHOMW7yFA);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i__j5Wg6rSPK6jprzM9co5KfZA, NI64 a__U8TO0Zlwhw51KAyAvquExw, NI64 b__hut4c5oxPM3l5OQ8nIwqqg);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, repr__nimwasm_317)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* x__jI9cccOjkZKaUuH9a29ceqC1Q);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_13)(NimStringV2* dest__C2JKGPCNdWKCPrsQvNywTQ);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, repr__nimwasm_327)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ x__jI9cccOjkZKaUuH9a29ceqC1Q_2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToRepr__nimwasm_331)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ x__O6sj0SPy1ZcNI5bVlpUuDg, NimStringV2 prefix__Y5NSkSYNRErbWBtpqxPBGg, NimStringV2 separator__x9ctR43EjJNjnDBK8a850iA, NimStringV2 suffix__WBC469clE5hhGNqhXqUJhmQ);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___stdZassertions_16)(NimStringV2* dest__9bysEU1F6xjkB13t7jg7tFg, NimStringV2 src__Q0EcxC6eCjA9adTTWfOBbQQ);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i__qyERKXYav6dUvCjr1Ll1Vg, NI n__JY89cybmZsK4EqibzwKjS2A);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, repr__systemZrepr95v50_22)(NU64 x__5YL0xGhia9a7UFO1zy9cnM5g);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_14)(NU64 x__KsYCTjO9co8rDpst8JJ2TVg);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_178)(NimStringV2 msg__K3q0fL6aLKe9by6qIeCq9c1A);
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__bQ89bat3hUkmJB4hVh79bf4w_2 = { 3 | NIM_STRLIT_FLAG, "nil" };
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_3 = {3, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_2};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__bQ89bat3hUkmJB4hVh79bf4w_4 = { 9 | NIM_STRLIT_FLAG, "RegionRef" };
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_5 = {9, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_4};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__bQ89bat3hUkmJB4hVh79bf4w_8 = { 2 | NIM_STRLIT_FLAG, ", " };
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_9 = {2, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_8};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__bQ89bat3hUkmJB4hVh79bf4w_12 = { 6 | NIM_STRLIT_FLAG, "offset" };
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_13 = {6, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_12};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__bQ89bat3hUkmJB4hVh79bf4w_14 = { 2 | NIM_STRLIT_FLAG, ": " };
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_15 = {2, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_14};
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_16 = {3, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_2};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__bQ89bat3hUkmJB4hVh79bf4w_17 = { 4 | NIM_STRLIT_FLAG, "ref " };
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_18 = {4, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_17};
static const struct {
  NI cap; NIM_CHAR data[140+1];
} TM__bQ89bat3hUkmJB4hVh79bf4w_20 = { 140 | NIM_STRLIT_FLAG, "/root/.choosenim/toolchains/nim-#devel/lib/system/iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_21 = {140, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_20};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__bQ89bat3hUkmJB4hVh79bf4w_22 = { 2 | NIM_STRLIT_FLAG, "@[" };
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_23 = {2, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_22};
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_24 = {2, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_8};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__bQ89bat3hUkmJB4hVh79bf4w_25 = { 1 | NIM_STRLIT_FLAG, "]" };
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_26 = {1, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_25};
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_27 = {2, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_8};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__bQ89bat3hUkmJB4hVh79bf4w_28 = { 8 | NIM_STRLIT_FLAG, "capacity" };
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_29 = {8, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_28};
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_30 = {2, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_14};
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_31 = {2, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_8};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__bQ89bat3hUkmJB4hVh79bf4w_32 = { 6 | NIM_STRLIT_FLAG, "length" };
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_33 = {6, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_32};
static const NimStringV2 TM__bQ89bat3hUkmJB4hVh79bf4w_34 = {2, (NimStrPayload*)&TM__bQ89bat3hUkmJB4hVh79bf4w_14};
extern NIM_BOOL nimInErrorMode__system_3267;
static N_INLINE(void, nimAddCharV1)(NimStringV2* s__S65jkNxJ72wMzHX9bQ0it8w, NIM_CHAR c__q53woDK9bF1K5bAKmsVpSkA) {
	NI TM__bQ89bat3hUkmJB4hVh79bf4w_6;
	NI TM__bQ89bat3hUkmJB4hVh79bf4w_7;
{	prepareAdd(s__S65jkNxJ72wMzHX9bQ0it8w, ((NI)1));
	(*(*s__S65jkNxJ72wMzHX9bQ0it8w).p).data[(*s__S65jkNxJ72wMzHX9bQ0it8w).len] = c__q53woDK9bF1K5bAKmsVpSkA;
	if (nimAddInt((*s__S65jkNxJ72wMzHX9bQ0it8w).len, ((NI)1), &TM__bQ89bat3hUkmJB4hVh79bf4w_6)) { raiseOverflow(); goto BeforeRet_;
	};
	(*(*s__S65jkNxJ72wMzHX9bQ0it8w).p).data[(NI)(TM__bQ89bat3hUkmJB4hVh79bf4w_6)] = 0;
	if (nimAddInt((*s__S65jkNxJ72wMzHX9bQ0it8w).len, ((NI)1), &TM__bQ89bat3hUkmJB4hVh79bf4w_7)) { raiseOverflow(); goto BeforeRet_;
	};
	(*s__S65jkNxJ72wMzHX9bQ0it8w).len = (NI)(TM__bQ89bat3hUkmJB4hVh79bf4w_7);
	}BeforeRet_: ;
}
static N_INLINE(void, nimCopyMem)(void* dest__HMDJtGX4ficduS9cTUiey0w, void* source__xDZEU1SRcEBuZ8mtbKQBhQ, NI size__9b8g0WMA1h1RvMwHOMW7yFA) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest__HMDJtGX4ficduS9cTUiey0w, source__xDZEU1SRcEBuZ8mtbKQBhQ, ((size_t) (size__9b8g0WMA1h1RvMwHOMW7yFA)));
}
static N_INLINE(void, copyMem__system_1751)(void* dest__fJYjxXM6yYjbZ9agQpPnNNA, void* source__Y6ZnHEKiVLswf16AMGuQUA, NI size__YLlwRG7Z9bTiXmiSwU9cUHeA) {
	nimCopyMem(dest__fJYjxXM6yYjbZ9agQpPnNNA, source__Y6ZnHEKiVLswf16AMGuQUA, size__YLlwRG7Z9bTiXmiSwU9cUHeA);
}
static N_INLINE(void, appendString)(NimStringV2* dest__Ws6Yi19bfxrbjCy9a9brzRV7A, NimStringV2 src__369aqaoei6FUsRf9cDAsKQ2g) {
{	{
		NI TM__bQ89bat3hUkmJB4hVh79bf4w_10;
		NI TM__bQ89bat3hUkmJB4hVh79bf4w_11;
		if (!(((NI)0) < src__369aqaoei6FUsRf9cDAsKQ2g.len)) goto LA3_;
		if (nimAddInt(src__369aqaoei6FUsRf9cDAsKQ2g.len, ((NI)1), &TM__bQ89bat3hUkmJB4hVh79bf4w_10)) { raiseOverflow(); goto BeforeRet_;
		};
		if (((NI)(TM__bQ89bat3hUkmJB4hVh79bf4w_10)) < ((NI)0) || ((NI)(TM__bQ89bat3hUkmJB4hVh79bf4w_10)) > ((NI)2147483647)){ raiseRangeErrorI((NI)(TM__bQ89bat3hUkmJB4hVh79bf4w_10), ((NI)0), ((NI)2147483647)); goto BeforeRet_;
		}
		copyMem__system_1751(((void*) ((&(*(*dest__Ws6Yi19bfxrbjCy9a9brzRV7A).p).data[(*dest__Ws6Yi19bfxrbjCy9a9brzRV7A).len]))), ((void*) ((&(*src__369aqaoei6FUsRf9cDAsKQ2g.p).data[((NI)0)]))), ((NI) ((NI)(TM__bQ89bat3hUkmJB4hVh79bf4w_10))));
		if (nimAddInt((*dest__Ws6Yi19bfxrbjCy9a9brzRV7A).len, src__369aqaoei6FUsRf9cDAsKQ2g.len, &TM__bQ89bat3hUkmJB4hVh79bf4w_11)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest__Ws6Yi19bfxrbjCy9a9brzRV7A).len = (NI)(TM__bQ89bat3hUkmJB4hVh79bf4w_11);
	}
	LA3_: ;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_3267);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, repr__systemZrepr95v50_22)(NU64 x__5YL0xGhia9a7UFO1zy9cnM5g) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result = dollar___systemZdollars_14(x__5YL0xGhia9a7UFO1zy9cnM5g);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToRepr__nimwasm_331)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ x__O6sj0SPy1ZcNI5bVlpUuDg, NimStringV2 prefix__Y5NSkSYNRErbWBtpqxPBGg, NimStringV2 separator__x9ctR43EjJNjnDBK8a850iA, NimStringV2 suffix__WBC469clE5hhGNqhXqUJhmQ) {
	NimStringV2 result;
	NIM_BOOL firstElement;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	eqcopy___stdZassertions_16((&result), prefix__Y5NSkSYNRErbWBtpqxPBGg);
	firstElement = NIM_TRUE;
	{
		NU8* value;
		NI i;
		NI L;
		NI T2_;
		value = (NU8*)0;
		i = ((NI)0);
		T2_ = x__O6sj0SPy1ZcNI5bVlpUuDg.len;
		L = T2_;
		{
			while (1) {
				NimStringV2 colontmpD_;
				NI TM__bQ89bat3hUkmJB4hVh79bf4w_19;
				if (!(i < L)) goto LA4				;
				colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
				if (i < 0 || i >= x__O6sj0SPy1ZcNI5bVlpUuDg.len){ raiseIndexError2(i,x__O6sj0SPy1ZcNI5bVlpUuDg.len-1); goto BeforeRet_;
				}
				value = (&x__O6sj0SPy1ZcNI5bVlpUuDg.p->data[i]);
				{
					if (!firstElement) goto LA7_;
					firstElement = NIM_FALSE;
				}
				goto LA5_;
				LA7_: ;
				{
					prepareAdd((&result), separator__x9ctR43EjJNjnDBK8a850iA.len + 0);
appendString((&result), separator__x9ctR43EjJNjnDBK8a850iA);
				}
				LA5_: ;
				colontmpD_ = repr__systemZrepr95v50_22(((NU64) ((*value))));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				prepareAdd((&result), colontmpD_.len + 0);
appendString((&result), colontmpD_);
				if (nimAddInt(i, ((NI)1), &TM__bQ89bat3hUkmJB4hVh79bf4w_19)) { raiseOverflow(); goto BeforeRet_;
				};
				i = (NI)(TM__bQ89bat3hUkmJB4hVh79bf4w_19);
				{
					NI T12_;
					T12_ = x__O6sj0SPy1ZcNI5bVlpUuDg.len;
					if (!!((T12_ == L))) goto LA13_;
					failedAssertImpl__stdZassertions_178(TM__bQ89bat3hUkmJB4hVh79bf4w_21);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				LA13_: ;
				eqdestroy___stdZassertions_13((&colontmpD_));
			} LA4: ;
		}
	}
	prepareAdd((&result), suffix__WBC469clE5hhGNqhXqUJhmQ.len + 0);
appendString((&result), suffix__WBC469clE5hhGNqhXqUJhmQ);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, repr__nimwasm_327)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ x__jI9cccOjkZKaUuH9a29ceqC1Q_2) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result = collectionToRepr__nimwasm_331(x__jI9cccOjkZKaUuH9a29ceqC1Q_2, TM__bQ89bat3hUkmJB4hVh79bf4w_23, TM__bQ89bat3hUkmJB4hVh79bf4w_24, TM__bQ89bat3hUkmJB4hVh79bf4w_26);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, repr__nimwasm_317)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* x__jI9cccOjkZKaUuH9a29ceqC1Q) {
	NimStringV2 result;
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	{
		if (!(x__jI9cccOjkZKaUuH9a29ceqC1Q == 0)) goto LA4_;
		result = TM__bQ89bat3hUkmJB4hVh79bf4w_16;
		eqdestroy___stdZassertions_13((&colontmpD_));
		goto BeforeRet_;
	}
	LA4_: ;
	result = TM__bQ89bat3hUkmJB4hVh79bf4w_18;
	colontmpD_ = repr__nimwasm_327((*x__jI9cccOjkZKaUuH9a29ceqC1Q));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	prepareAdd((&result), colontmpD_.len + 0);
appendString((&result), colontmpD_);
	{
		LA1_:;
	}
	{
		eqdestroy___stdZassertions_13((&colontmpD_));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, reprObject__nimwasm_304)(NimStringV2* res__Ts4Qs0N3SWIpMcs766LXNg, tyObject_Region__rcaGGUGHuXUOkC68lX2yPA x__DBOUjt6X9bDPwP3S5jEmWYA) {
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	NimStringV2 colontmpD__3;
	NIM_BOOL firstElement;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
	nimAddCharV1((&(*res__Ts4Qs0N3SWIpMcs766LXNg)), 40);
	firstElement = NIM_TRUE;
	{
		if (!!(firstElement)) goto LA3_;
		prepareAdd((&(*res__Ts4Qs0N3SWIpMcs766LXNg)), 2);
appendString((&(*res__Ts4Qs0N3SWIpMcs766LXNg)), TM__bQ89bat3hUkmJB4hVh79bf4w_9);
	}
	LA3_: ;
	prepareAdd((&(*res__Ts4Qs0N3SWIpMcs766LXNg)), 6);
appendString((&(*res__Ts4Qs0N3SWIpMcs766LXNg)), TM__bQ89bat3hUkmJB4hVh79bf4w_13);
	prepareAdd((&(*res__Ts4Qs0N3SWIpMcs766LXNg)), 2);
appendString((&(*res__Ts4Qs0N3SWIpMcs766LXNg)), TM__bQ89bat3hUkmJB4hVh79bf4w_15);
	colontmpD_ = repr__nimwasm_317(x__DBOUjt6X9bDPwP3S5jEmWYA.offset);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	prepareAdd((&(*res__Ts4Qs0N3SWIpMcs766LXNg)), colontmpD_.len + 0);
appendString((&(*res__Ts4Qs0N3SWIpMcs766LXNg)), colontmpD_);
	firstElement = NIM_FALSE;
	{
		if (!!(firstElement)) goto LA7_;
		prepareAdd((&(*res__Ts4Qs0N3SWIpMcs766LXNg)), 2);
appendString((&(*res__Ts4Qs0N3SWIpMcs766LXNg)), TM__bQ89bat3hUkmJB4hVh79bf4w_27);
	}
	LA7_: ;
	prepareAdd((&(*res__Ts4Qs0N3SWIpMcs766LXNg)), 8);
appendString((&(*res__Ts4Qs0N3SWIpMcs766LXNg)), TM__bQ89bat3hUkmJB4hVh79bf4w_29);
	prepareAdd((&(*res__Ts4Qs0N3SWIpMcs766LXNg)), 2);
appendString((&(*res__Ts4Qs0N3SWIpMcs766LXNg)), TM__bQ89bat3hUkmJB4hVh79bf4w_30);
	colontmpD__2 = repr__systemZrepr95v50_22(((NU64) (x__DBOUjt6X9bDPwP3S5jEmWYA.capacity)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	prepareAdd((&(*res__Ts4Qs0N3SWIpMcs766LXNg)), colontmpD__2.len + 0);
appendString((&(*res__Ts4Qs0N3SWIpMcs766LXNg)), colontmpD__2);
	firstElement = NIM_FALSE;
	{
		if (!!(firstElement)) goto LA11_;
		prepareAdd((&(*res__Ts4Qs0N3SWIpMcs766LXNg)), 2);
appendString((&(*res__Ts4Qs0N3SWIpMcs766LXNg)), TM__bQ89bat3hUkmJB4hVh79bf4w_31);
	}
	LA11_: ;
	prepareAdd((&(*res__Ts4Qs0N3SWIpMcs766LXNg)), 6);
appendString((&(*res__Ts4Qs0N3SWIpMcs766LXNg)), TM__bQ89bat3hUkmJB4hVh79bf4w_33);
	prepareAdd((&(*res__Ts4Qs0N3SWIpMcs766LXNg)), 2);
appendString((&(*res__Ts4Qs0N3SWIpMcs766LXNg)), TM__bQ89bat3hUkmJB4hVh79bf4w_34);
	colontmpD__3 = repr__systemZrepr95v50_22(((NU64) (x__DBOUjt6X9bDPwP3S5jEmWYA.length)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	prepareAdd((&(*res__Ts4Qs0N3SWIpMcs766LXNg)), colontmpD__3.len + 0);
appendString((&(*res__Ts4Qs0N3SWIpMcs766LXNg)), colontmpD__3);
	firstElement = NIM_FALSE;
	nimAddCharV1((&(*res__Ts4Qs0N3SWIpMcs766LXNg)), 41);
	eqdestroy___stdZassertions_13((&colontmpD__3));
	eqdestroy___stdZassertions_13((&colontmpD__2));
	eqdestroy___stdZassertions_13((&colontmpD_));
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, repr__nimwasm_292)(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* x__jI9cccOjkZKaUuH9a29ceqC1Q) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	{
		if (!(x__jI9cccOjkZKaUuH9a29ceqC1Q == 0)) goto LA3_;
		result = TM__bQ89bat3hUkmJB4hVh79bf4w_3;
		goto BeforeRet_;
	}
	LA3_: ;
	result = TM__bQ89bat3hUkmJB4hVh79bf4w_5;
	reprObject__nimwasm_304((&result), (*x__jI9cccOjkZKaUuH9a29ceqC1Q));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
