/* Generated by Nim Compiler v1.9.1 */
/* Compiled for: Linux, i386, clang */
/* Command for C compiler:
   /usr/bin/clang-15 -c -w -ferror-limit=3 --target=wasm32-unknown-unknown-wasm -I/usr/include -flto -fvisibility=hidden -nostdlib -fdata-sections -ffunction-sections -DPRINTF_DISABLE_SUPPORT_FLOAT=1 -DPRINTF_DISABLE_SUPPORT_LONG_LONG=1 -DPRINTF_DISABLE_SUPPORT_PTRDIFF_T=1 -Os  -fPIC  -I'/root/.choosenim/toolchains/nim-#devel/lib' -I/root/wasmrt -o /root/wasmrt/nimcache/@m..@s.choosenim@stoolchains@snim-@hdevel@slib@ssystem@sdollars.nim.c.o /root/wasmrt/nimcache/@m..@s.choosenim@stoolchains@snim-@hdevel@slib@ssystem@sdollars.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
N_LIB_PRIVATE N_NIMCALL(void, addInt__stdZprivateZdigitsutils_161)(NimStringV2* result__eysCSqL57sYgaohCkVYRVg, NI64 x__ei4a8HqkfxKmzlWy521zOg);
static N_INLINE(void, addInt__stdZprivateZdigitsutils_183)(NimStringV2* result__eysCSqL57sYgaohCkVYRVg_2, NI x__ei4a8HqkfxKmzlWy521zOg_2);
static N_INLINE(void, addInt__stdZprivateZdigitsutils_183)(NimStringV2* result__eysCSqL57sYgaohCkVYRVg_2, NI x__ei4a8HqkfxKmzlWy521zOg_2) {
	addInt__stdZprivateZdigitsutils_161(result__eysCSqL57sYgaohCkVYRVg_2, ((NI64) (x__ei4a8HqkfxKmzlWy521zOg_2)));
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_8)(NI x__KsYCTjO9co8rDpst8JJ2TVg_2) {
	NimStringV2 result;
	result.len = 0; result.p = NIM_NIL;
	addInt__stdZprivateZdigitsutils_183((&result), x__KsYCTjO9co8rDpst8JJ2TVg_2);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_11)(NI64 x__KsYCTjO9co8rDpst8JJ2TVg) {
	NimStringV2 result;
	result.len = 0; result.p = NIM_NIL;
	addInt__stdZprivateZdigitsutils_161((&result), x__KsYCTjO9co8rDpst8JJ2TVg);
	return result;
}
