/* Generated by Nim Compiler v1.9.1 */
/* Compiled for: Linux, i386, clang */
/* Command for C compiler:
   /usr/bin/clang-15 -c -w -ferror-limit=3 --target=wasm32-unknown-unknown-wasm -I/usr/include -flto -fvisibility=hidden -nostdlib -fdata-sections -ffunction-sections -DPRINTF_DISABLE_SUPPORT_FLOAT=1 -DPRINTF_DISABLE_SUPPORT_LONG_LONG=1 -DPRINTF_DISABLE_SUPPORT_PTRDIFF_T=1 -Os  -fPIC  -I'/root/.choosenim/toolchains/nim-#devel/lib' -I/root/wasmrt -o /root/wasmrt/nimcache/@mnimwasm.nim.c.o /root/wasmrt/nimcache/@mnimwasm.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_Region__rcaGGUGHuXUOkC68lX2yPA tyObject_Region__rcaGGUGHuXUOkC68lX2yPA;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
typedef struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct tyObject_Region__rcaGGUGHuXUOkC68lX2yPA {
NU8* offset;
NU32 capacity;
NU32 length;
};
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content* p;
};
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A {
NI rc;
};
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};


#ifndef tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content_PP
#define tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content_PP
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content { NI cap; NU8 data[SEQ_DECL_SIZE];};
#endif

      __attribute__ ((visibility ("default"))) void interface_version_8(void);
__attribute__ ((visibility ("default"))) tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* allocate(NU32 size__Ub4llh9c9bk9cDKFEroTU8U9cw);
static N_INLINE(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA*, allocate_internal__nimwasm_225)(NU32 size__GFfjtQqi09cnnFadibV7FJA);
N_LIB_PRIVATE N_NIMCALL(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA*, newRegioOfCap__nimwasm_201)(NU32 capacity__5pqcyHFVIrpNURwaBwwqLQ);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, newSeq__nimwasm_150)(NI len__p49b9b5HIylhMqZoxjxlq7QA);
N_LIB_PRIVATE N_NIMCALL(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA*, newRegion__nimwasm_9)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ data__RF9cKYd0XNujuK5gDZtmS5g);
static N_INLINE(NU8*, create__nimwasm_16)(NI size__QKX6RUrjXs8A9caITDH0erQ);
N_LIB_PRIVATE N_NOCONV(void*, alloc0Impl__system_1769)(NI size__4KerptJEDen31kAmPf36WQ);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size__LZn6dneMVUSD9cVJcoc7Slw, NI alignment__eu9b1Xf7SGvOM5v8REyXVWA);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___nimwasm_158)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* dest__roU2YOy9a9a9beBr400TJtMRA);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, GC_ref__nimwasm_228)(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* x__mTTscJMWe8EH0mjWxuOV7Q);
__attribute__ ((visibility ("default"))) void deallocate(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* region__Cxm7Ay3a6xg8n49cIQLn0TQ);
static N_INLINE(void, deallocate_internal__nimwasm_242)(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* region__X79bWR1LzTRhQVBz4vEmMVg);
N_LIB_PRIVATE N_NIMCALL(void, GC_unref__nimwasm_244)(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* x__6zAWnA9cBjzBqy01DGNVb3w);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p__YLyUZk8Vki03tNo3UlpTrw);
static N_INLINE(NI, minuspercent___system_790)(NI x__nhqJNug5PDvy9ah8vc6uJ5Q, NI y__LJLJ0MGnpTb2U2nvMvG6MQ);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___nimwasm_40)(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* dest__1mZ1xPq9bm6Yt9cL0jlGm41w);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p__fgKDMBQtwelfRnNv9bB0I5Q, NI alignment__upwtGXrI1BTnjD4u6YvIRw);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p__1Ef17pd0N75MzUBHEC131Q);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, consume__nimwasm_212)(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* region__aMCmvdbBzJS9cGv7gcB5tNA);
__attribute__ ((visibility ("default"))) tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* instantiate(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* ptr0__bIrokdQivKCTfOHd69bkIEg, tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* ptr1__uqAaKbT9cXxqxW6JUyBPchQ, tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* ptr2__YO6rLX8KEaeuHUIFWruFJw);
N_LIB_PRIVATE N_NIMCALL(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA*, instantiate_internal__nimwasm_258)(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* env_ptr__kYCuIYE1829auvDihFN9b6hw, tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* info_ptr__P2Qa3rhNa6JfMoL4Vln68Q, tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* msg_ptr__v9bMeAl4b5RHs3gPRNzE8wg);
N_LIB_PRIVATE N_NIMCALL(void, debug__nimwasm_61)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ msg__JO9bBcXbL6ZMmKrZUNTYnMQ);
N_LIB_PRIVATE N_NIMCALL(void, debug__nimwasm_7)(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* source_ptr__htcD6i9bQCNcOdoTawx7zFQ);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___nimwasm_49)(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA** dest__1mZ1xPq9bm6Yt9cL0jlGm41w);
N_LIB_PRIVATE N_NIMCALL(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA*, newRegion__nimwasm_185)(NimStringV2 data__RF9cKYd0XNujuK5gDZtmS5g_2);
__attribute__ ((visibility ("default"))) tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* execute(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* ptr0__nHppPOHf4CCpTQxWUw5D8A, tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* ptr1__lugP8mCOx6l8sxwjAviIRQ, tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* ptr2__V08U9cs1QCscAL2dqeQSmfA);
N_LIB_PRIVATE N_NIMCALL(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA*, execute_internal__nimwasm_275)(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* env_ptr__sNAoQ9bej68Sgw3SMXCl9clQ, tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* info_ptr__FcwFN12AU2bIPXvw1y0YUg, tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* msg_ptr__9aFWxnYcHSTiFxTQODyvvQg);
__attribute__ ((visibility ("default"))) tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* query(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* ptr0__6rR9aI4VJ7S5CkafNJRApRw, tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* ptr1__Wxyz0sJa7CYyfeh5tF9b9aOQ);
N_LIB_PRIVATE N_NIMCALL(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA*, query_internal__nimwasm_288)(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* env_ptr__gPwqMvPEiAQDrUxb8r9amKg, tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* msg_ptr__qxP5s51Bg8MeianUl5e8DA);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotchoosenimatstoolchainsatsnimminusathdevelatslibatssystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
static const struct {
  NI cap; NIM_CHAR data[62+1];
} TM__CSDI7ZNjPPjF8Y9cXdypcpA_2 = { 62 | NIM_STRLIT_FLAG, "{\"Ok\":{\"messages\":[],\"attributes\":[],\"events\":[],\"data\":null}}" };
static const NimStringV2 TM__CSDI7ZNjPPjF8Y9cXdypcpA_3 = {62, (NimStrPayload*)&TM__CSDI7ZNjPPjF8Y9cXdypcpA_2};
static const NimStringV2 TM__CSDI7ZNjPPjF8Y9cXdypcpA_4 = {62, (NimStrPayload*)&TM__CSDI7ZNjPPjF8Y9cXdypcpA_2};
static const struct {
  NI cap; NIM_CHAR data[29+1];
} TM__CSDI7ZNjPPjF8Y9cXdypcpA_5 = { 29 | NIM_STRLIT_FLAG, "{\"ok\":\"SGVsbG8gZnJvbSBOaW0h\"}" };
static const NimStringV2 TM__CSDI7ZNjPPjF8Y9cXdypcpA_6 = {29, (NimStrPayload*)&TM__CSDI7ZNjPPjF8Y9cXdypcpA_5};
extern NIM_BOOL nimInErrorMode__system_3267;
__attribute__ ((visibility ("default"))) void interface_version_8(void) {
}
static N_INLINE(NU8*, create__nimwasm_16)(NI size__QKX6RUrjXs8A9caITDH0erQ) {
	NU8* result;
	void* T1_;
	result = (NU8*)0;
	T1_ = (void*)0;
	T1_ = alloc0Impl__system_1769(((NI) ((NI)(((NI)1) * ((NI) (size__QKX6RUrjXs8A9caITDH0erQ))))));
	result = ((NU8*) (T1_));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA*, newRegion__nimwasm_9)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ data__RF9cKYd0XNujuK5gDZtmS5g) {
	tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* result;
	NU8* buf;
	NI T1_;
	NU8* buf_data;
	tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* T6_;
	NI T7_;
	NI T8_;
	result = NIM_NIL;
	T1_ = data__RF9cKYd0XNujuK5gDZtmS5g.len;
	buf = create__nimwasm_16(((NI) (T1_)));
	buf_data = ((NU8*) (buf));
	{
		NI i;
		NI colontmp_;
		NI T3_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		T3_ = data__RF9cKYd0XNujuK5gDZtmS5g.len;
		colontmp_ = T3_;
		i_2 = ((NI)0);
		{
			while (1) {
				if (!(i_2 < colontmp_)) goto LA5				;
				i = i_2;
				buf_data[i] = data__RF9cKYd0XNujuK5gDZtmS5g.p->data[i];
				i_2 += ((NI)1);
			} LA5: ;
		}
	}
	T6_ = NIM_NIL;
	T6_ = (tyObject_Region__rcaGGUGHuXUOkC68lX2yPA*) nimNewObj(sizeof(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA), NIM_ALIGNOF(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA));
	result = T6_;
	(*result).offset = buf;
	T7_ = data__RF9cKYd0XNujuK5gDZtmS5g.len;
	(*result).capacity = ((NU32) (T7_));
	T8_ = data__RF9cKYd0XNujuK5gDZtmS5g.len;
	(*result).length = ((NU32) (T8_));
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_3267);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA*, newRegioOfCap__nimwasm_201)(NU32 capacity__5pqcyHFVIrpNURwaBwwqLQ) {
	tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* result;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ data;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	data.len = 0; data.p = NIM_NIL;
	data = newSeq__nimwasm_150(((NI) (capacity__5pqcyHFVIrpNURwaBwwqLQ)));
	result = newRegion__nimwasm_9(data);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___nimwasm_158((&data));
	}BeforeRet_: ;
	return result;
}
static N_INLINE(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA*, allocate_internal__nimwasm_225)(NU32 size__GFfjtQqi09cnnFadibV7FJA) {
	tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	result = newRegioOfCap__nimwasm_201(size__GFfjtQqi09cnnFadibV7FJA);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	GC_ref__nimwasm_228(result);
	}BeforeRet_: ;
	return result;
}
__attribute__ ((visibility ("default"))) tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* allocate(NU32 size__Ub4llh9c9bk9cDKFEroTU8U9cw) {
	tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	result = allocate_internal__nimwasm_225(size__Ub4llh9c9bk9cDKFEroTU8U9cw);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, minuspercent___system_790)(NI x__nhqJNug5PDvy9ah8vc6uJ5Q, NI y__LJLJ0MGnpTb2U2nvMvG6MQ) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x__nhqJNug5PDvy9ah8vc6uJ5Q))) - (NU32)(((NU) (y__LJLJ0MGnpTb2U2nvMvG6MQ))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p__YLyUZk8Vki03tNo3UlpTrw) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* cell;
		NI T5_;
		if (!!((p__YLyUZk8Vki03tNo3UlpTrw == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_790(((NI) (ptrdiff_t) (p__YLyUZk8Vki03tNo3UlpTrw)), ((NI)4));
		cell = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_));
		{
			if (!((NI)((*cell).rc & ((NI)-8)) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
		LA8_: ;
		{
			(*cell).rc -= ((NI)8);
		}
		LA6_: ;
	}
	LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___nimwasm_40)(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* dest__1mZ1xPq9bm6Yt9cL0jlGm41w) {
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___nimwasm_49)(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA** dest__1mZ1xPq9bm6Yt9cL0jlGm41w) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest__1mZ1xPq9bm6Yt9cL0jlGm41w));
		if (!T3_) goto LA4_;
		eqdestroy___nimwasm_40((*dest__1mZ1xPq9bm6Yt9cL0jlGm41w));
		nimRawDispose((*dest__1mZ1xPq9bm6Yt9cL0jlGm41w), ((NI)4));
	}
	LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, consume__nimwasm_212)(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* region__aMCmvdbBzJS9cGv7gcB5tNA) {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ result;
	NU8* data;
	result.len = 0; result.p = NIM_NIL;
	result = newSeq__nimwasm_150(((NI) ((*region__aMCmvdbBzJS9cGv7gcB5tNA).length)));
	data = ((NU8*) ((*region__aMCmvdbBzJS9cGv7gcB5tNA).offset));
	{
		NU32 i;
		NU32 res;
		i = (NU32)0;
		res = ((NU32)0);
		{
			while (1) {
				if (!((NU32)(res) < (NU32)((*region__aMCmvdbBzJS9cGv7gcB5tNA).length))) goto LA3				;
				i = res;
				result.p->data[i] = data[i];
				res += ((NI)1);
			} LA3: ;
		}
	}
	return result;
}
static N_INLINE(void, deallocate_internal__nimwasm_242)(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* region__X79bWR1LzTRhQVBz4vEmMVg) {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ colontmpD_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	GC_unref__nimwasm_244(region__X79bWR1LzTRhQVBz4vEmMVg);
	dealloc(((void*) ((*region__X79bWR1LzTRhQVBz4vEmMVg).offset)));
	colontmpD_ = consume__nimwasm_212(region__X79bWR1LzTRhQVBz4vEmMVg);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(void)(colontmpD_);
	eqdestroy___nimwasm_158((&colontmpD_));
	}BeforeRet_: ;
}
__attribute__ ((visibility ("default"))) void deallocate(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* region__Cxm7Ay3a6xg8n49cIQLn0TQ) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	deallocate_internal__nimwasm_242(region__Cxm7Ay3a6xg8n49cIQLn0TQ);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, debug__nimwasm_7)(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* source_ptr__htcD6i9bQCNcOdoTawx7zFQ) {
}
N_LIB_PRIVATE N_NIMCALL(void, debug__nimwasm_61)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ msg__JO9bBcXbL6ZMmKrZUNTYnMQ) {
	tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* region;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	region = NIM_NIL;
	region = newRegion__nimwasm_9(msg__JO9bBcXbL6ZMmKrZUNTYnMQ);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	debug__nimwasm_7(region);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___nimwasm_49(&region);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA*, newRegion__nimwasm_185)(NimStringV2 data__RF9cKYd0XNujuK5gDZtmS5g_2) {
	tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* result;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ buf;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	buf.len = 0; buf.p = NIM_NIL;
	buf = newSeq__nimwasm_150(((NI) (data__RF9cKYd0XNujuK5gDZtmS5g_2.len)));
	{
		NI i;
		NI colontmp_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = data__RF9cKYd0XNujuK5gDZtmS5g_2.len;
		i_2 = ((NI)0);
		{
			while (1) {
				if (!(i_2 < colontmp_)) goto LA3				;
				i = i_2;
				buf.p->data[i] = ((NU8) (((NU8)(data__RF9cKYd0XNujuK5gDZtmS5g_2.p->data[i]))));
				i_2 += ((NI)1);
			} LA3: ;
		}
	}
	result = newRegion__nimwasm_9(buf);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___nimwasm_158((&buf));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA*, instantiate_internal__nimwasm_258)(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* env_ptr__kYCuIYE1829auvDihFN9b6hw, tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* info_ptr__P2Qa3rhNa6JfMoL4Vln68Q, tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* msg_ptr__v9bMeAl4b5RHs3gPRNzE8wg) {
	tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* result;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ env;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ info;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ msg;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	env.len = 0; env.p = NIM_NIL;
	info.len = 0; info.p = NIM_NIL;
	msg.len = 0; msg.p = NIM_NIL;
	env = consume__nimwasm_212(env_ptr__kYCuIYE1829auvDihFN9b6hw);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	info = consume__nimwasm_212(info_ptr__P2Qa3rhNa6JfMoL4Vln68Q);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	msg = consume__nimwasm_212(msg_ptr__v9bMeAl4b5RHs3gPRNzE8wg);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	debug__nimwasm_61(env);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	debug__nimwasm_61(info);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	debug__nimwasm_61(msg);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = newRegion__nimwasm_185(TM__CSDI7ZNjPPjF8Y9cXdypcpA_3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___nimwasm_158((&msg));
	eqdestroy___nimwasm_158((&info));
	eqdestroy___nimwasm_158((&env));
	}BeforeRet_: ;
	return result;
}
__attribute__ ((visibility ("default"))) tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* instantiate(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* ptr0__bIrokdQivKCTfOHd69bkIEg, tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* ptr1__uqAaKbT9cXxqxW6JUyBPchQ, tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* ptr2__YO6rLX8KEaeuHUIFWruFJw) {
	tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	result = instantiate_internal__nimwasm_258(ptr0__bIrokdQivKCTfOHd69bkIEg, ptr1__uqAaKbT9cXxqxW6JUyBPchQ, ptr2__YO6rLX8KEaeuHUIFWruFJw);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA*, execute_internal__nimwasm_275)(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* env_ptr__sNAoQ9bej68Sgw3SMXCl9clQ, tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* info_ptr__FcwFN12AU2bIPXvw1y0YUg, tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* msg_ptr__9aFWxnYcHSTiFxTQODyvvQg) {
	tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* result;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ env;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ info;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ msg;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	env.len = 0; env.p = NIM_NIL;
	info.len = 0; info.p = NIM_NIL;
	msg.len = 0; msg.p = NIM_NIL;
	env = consume__nimwasm_212(env_ptr__sNAoQ9bej68Sgw3SMXCl9clQ);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	info = consume__nimwasm_212(info_ptr__FcwFN12AU2bIPXvw1y0YUg);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	msg = consume__nimwasm_212(msg_ptr__9aFWxnYcHSTiFxTQODyvvQg);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	debug__nimwasm_61(env);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	debug__nimwasm_61(info);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	debug__nimwasm_61(msg);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = newRegion__nimwasm_185(TM__CSDI7ZNjPPjF8Y9cXdypcpA_4);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___nimwasm_158((&msg));
	eqdestroy___nimwasm_158((&info));
	eqdestroy___nimwasm_158((&env));
	}BeforeRet_: ;
	return result;
}
__attribute__ ((visibility ("default"))) tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* execute(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* ptr0__nHppPOHf4CCpTQxWUw5D8A, tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* ptr1__lugP8mCOx6l8sxwjAviIRQ, tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* ptr2__V08U9cs1QCscAL2dqeQSmfA) {
	tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	result = execute_internal__nimwasm_275(ptr0__nHppPOHf4CCpTQxWUw5D8A, ptr1__lugP8mCOx6l8sxwjAviIRQ, ptr2__V08U9cs1QCscAL2dqeQSmfA);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA*, query_internal__nimwasm_288)(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* env_ptr__gPwqMvPEiAQDrUxb8r9amKg, tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* msg_ptr__qxP5s51Bg8MeianUl5e8DA) {
	tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* result;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ env;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ msg;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	env.len = 0; env.p = NIM_NIL;
	msg.len = 0; msg.p = NIM_NIL;
	env = consume__nimwasm_212(env_ptr__gPwqMvPEiAQDrUxb8r9amKg);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	msg = consume__nimwasm_212(msg_ptr__qxP5s51Bg8MeianUl5e8DA);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	debug__nimwasm_61(env);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	debug__nimwasm_61(msg);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = newRegion__nimwasm_185(TM__CSDI7ZNjPPjF8Y9cXdypcpA_6);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___nimwasm_158((&msg));
	eqdestroy___nimwasm_158((&env));
	}BeforeRet_: ;
	return result;
}
__attribute__ ((visibility ("default"))) tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* query(tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* ptr0__6rR9aI4VJ7S5CkafNJRApRw, tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* ptr1__Wxyz0sJa7CYyfeh5tF9b9aOQ) {
	tyObject_Region__rcaGGUGHuXUOkC68lX2yPA* result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	result = query_internal__nimwasm_288(ptr0__6rR9aI4VJ7S5CkafNJRApRw, ptr1__Wxyz0sJa7CYyfeh5tF9b9aOQ);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE void PreMainInner(void) {
}

N_LIB_PRIVATE void PreMain(void) {
	#if 0
	void (*volatile inner)(void);
	inner = PreMainInner;
	atmdotdotatsdotchoosenimatstoolchainsatsnimminusathdevelatslibatssystemdotnim_Init000();
	(*inner)();
	#else
	atmdotdotatsdotchoosenimatstoolchainsatsnimminusathdevelatslibatssystemdotnim_Init000();
	PreMainInner();
	#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_LIB_EXPORT N_CDECL(void, NimMain)(void) {
	#if 0
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
	#else
	PreMain();
	NimMainInner();
	#endif
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
}
}

