/* Generated by Nim Compiler v1.9.1 */
/* Compiled for: Linux, i386, clang */
/* Command for C compiler:
   /usr/bin/clang-15 -c -w -ferror-limit=3 --target=wasm32-unknown-unknown-wasm -I/usr/include -flto -fvisibility=hidden -nostdlib -fdata-sections -ffunction-sections -DPRINTF_DISABLE_SUPPORT_FLOAT=1 -DPRINTF_DISABLE_SUPPORT_LONG_LONG=1 -DPRINTF_DISABLE_SUPPORT_PTRDIFF_T=1 -Os  -fPIC  -I'/root/.choosenim/toolchains/nim-#devel/lib' -I/root/wasmrt -o /root/wasmrt/nimcache/@mwasmrt.nim.c.o /root/wasmrt/nimcache/@mwasmrt.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
int stdout = 0;
int stderr = 1;
static int dummyErrno = 0;

N_LIB_PRIVATE void* memcpy(void* a, const void* b, size_t s) {
  char* aa = (char*)a;
  char* bb = (char*)b;
  while(s) {
    --s;
    *aa = *bb;
    ++aa;
    ++bb;
  }
  return a;
}

N_LIB_PRIVATE void* memmove(void *dest, const void *src, size_t len) { /* Copied from https://code.woboq.org/gcc/libgcc/memmove.c.html */
  char *d = dest;
  const char *s = src;
  if (d < s)
    while (len--)
      *d++ = *s++;
  else {
    char *lasts = s + (len-1);
    char *lastd = d + (len-1);
    while (len--)
      *lastd-- = *lasts--;
  }
  return dest;
}

N_LIB_PRIVATE void* memchr(register const void* src_void, int c, size_t length) { /* Copied from https://code.woboq.org/gcc/libiberty/memchr.c.html */
  const unsigned char *src = (const unsigned char *)src_void;

  while (length-- > 0) {
    if (*src == c)
     return (void*)src;
    src++;
  }
  return NULL;
}

N_LIB_PRIVATE int memcmp(const void* a, const void* b, size_t s) {
  char* aa = (char*)a;
  char* bb = (char*)b;
  if (aa == bb) return 0;

  while(s) {
    --s;
    int ia = *aa;
    int ib = *bb;
    int r = ia - ib; // TODO: The result might be inverted. Verify against C standard.
    if (r) return r;
    *aa = *bb;
    ++aa;
    ++bb;
  }
  return 0;
}

N_LIB_PRIVATE void* memset(void* a, int b, size_t s) {
  char* aa = (char*)a;
  while(s) {
    --s;
    *aa = b;
    ++aa;
  }
  return a;
}

N_LIB_PRIVATE size_t strlen(const char* a) {
  const char* b = a;
  while (*b++);
  return b - a - 1;
}

N_LIB_PRIVATE char* strerror(int errnum) {
  return "strerror is not supported";
}

N_LIB_PRIVATE int* __errno_location() {
  return &dummyErrno;
}

N_LIB_PRIVATE char* strstr(char *haystack, const char *needle) {
  if (haystack == NULL || needle == NULL) {
    return NULL;
  }

  for ( ; *haystack; haystack++) {
    // Is the needle at this point in the haystack?
    const char *h, *n;
    for (h = haystack, n = needle; *h && *n && (*h == *n); ++h, ++n) {
      // Match is progressing
    }
    if (*n == '\0') {
      // Found match!
      return haystack;
    }
    // Didn't match here.  Try again further along haystack.
  }
  return NULL;
}

N_LIB_PRIVATE N_NIMCALL(void*, mmap)(void* a__0Bj0TaVfbmvIWJFpEc9a9clw, size_t len__j3PnzvbJlwlME5DxkwQHgQ, int prot__1jRB7p0RDkPQ08TC4v10bg, int flags__P2jZOVhiKoMW9cnA7dm9aepg, int fildes__0gto1fNP9aJomAgxfGLb9bTg, NI off__UKF9b9a0uWOCykcE6wNLy9aCQ);
static N_INLINE(void*, wasmAlloc__wasmrt_72)(NU block_size__RY0fkaKhHm8qmlkr3ST6Gw);
static N_INLINE(NI32, wasmMemoryGrow__wasmrt_64)(NI32 b__hl9a4ntyLyFxVwOmq4kkNbg);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(int, munmap)(void* a__CbTPKUTd67RI9cebv69cB2UA, size_t len__9cziGYS2a75nPqop1w4qYWw);
N_LIB_PRIVATE N_NIMCALL(size_t, fwrite)(void* p__gZL4784pBi6gZfjuVGG8fg, size_t sz__mmfmwMRZELhnzxAffWfIXg, size_t nmemb__mpd3GUFsFTAjmOBLZn5gJQ, void* stream__lhNaPAtW1yTqMbypGRS0cQ);
N_LIB_PRIVATE N_NIMCALL(void, exit)(int code__zrPAqFArfzJEYHo9bTITKkw);
N_LIB_PRIVATE N_NIMCALL(int, fflush)(void* stream__bCkp8dmVguW07m8JreNv8Q);
N_LIB_PRIVATE NU memStart__wasmrt_70;
N_LIB_PRIVATE NU totalMemory__wasmrt_71;
extern NIM_BOOL nimInErrorMode__system_3267;
static N_INLINE(NI32, wasmMemoryGrow__wasmrt_64)(NI32 b__hl9a4ntyLyFxVwOmq4kkNbg) {
	NI32 result;
	result = (NI32)0;
	__builtin_wasm_memory_grow(((NI32)0), b__hl9a4ntyLyFxVwOmq4kkNbg);
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_3267);
	return result;
}
static N_INLINE(void*, wasmAlloc__wasmrt_72)(NU block_size__RY0fkaKhHm8qmlkr3ST6Gw) {
	void* result;
	NU availableMemory;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (void*)0;
	{
		NI32 T5_;
		if (!(totalMemory__wasmrt_71 == ((NU)0))) goto LA3_;
		T5_ = (NI32)0;
		T5_ = __builtin_wasm_memory_size(((NI32)0));
		totalMemory__wasmrt_71 = (NU)((NU32)(((NU) (T5_))) * (NU32)(((NU)65536)));
		memStart__wasmrt_70 = totalMemory__wasmrt_71;
	}
	LA3_: ;
	result = ((void*) (memStart__wasmrt_70));
	availableMemory = (NU)((NU32)(totalMemory__wasmrt_71) - (NU32)(memStart__wasmrt_70));
	memStart__wasmrt_70 += block_size__RY0fkaKhHm8qmlkr3ST6Gw;
	{
		NU wasmPagesToAllocate;
		NI32 oldPages;
		if (!((NU32)(availableMemory) < (NU32)(block_size__RY0fkaKhHm8qmlkr3ST6Gw))) goto LA8_;
		wasmPagesToAllocate = (NU)((NU32)((NU)((NU32)(block_size__RY0fkaKhHm8qmlkr3ST6Gw) / (NU32)(((NU)65536)))) + (NU32)(((NU)1)));
		oldPages = wasmMemoryGrow__wasmrt_64(((NI32) (wasmPagesToAllocate)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		{
			if (!(oldPages < ((NI32)0))) goto LA12_;
			result = NIM_NIL;
			goto BeforeRet_;
		}
		LA12_: ;
		totalMemory__wasmrt_71 += (NU)((NU32)(wasmPagesToAllocate) * (NU32)(((NU)65536)));
	}
	LA8_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, mmap)(void* a__0Bj0TaVfbmvIWJFpEc9a9clw, size_t len__j3PnzvbJlwlME5DxkwQHgQ, int prot__1jRB7p0RDkPQ08TC4v10bg, int flags__P2jZOVhiKoMW9cnA7dm9aepg, int fildes__0gto1fNP9aJomAgxfGLb9bTg, NI off__UKF9b9a0uWOCykcE6wNLy9aCQ) {
	void* result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (void*)0;
	{
		if (!!((a__0Bj0TaVfbmvIWJFpEc9a9clw == NIM_NIL))) goto LA3_;
	}
	LA3_: ;
	result = wasmAlloc__wasmrt_72(len__j3PnzvbJlwlME5DxkwQHgQ);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(int, munmap)(void* a__CbTPKUTd67RI9cebv69cB2UA, size_t len__9cziGYS2a75nPqop1w4qYWw) {
	int result;
	result = (int)0;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(size_t, fwrite)(void* p__gZL4784pBi6gZfjuVGG8fg, size_t sz__mmfmwMRZELhnzxAffWfIXg, size_t nmemb__mpd3GUFsFTAjmOBLZn5gJQ, void* stream__lhNaPAtW1yTqMbypGRS0cQ) {
	size_t result;
	result = (size_t)0;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, exit)(int code__zrPAqFArfzJEYHo9bTITKkw) {
}
N_LIB_PRIVATE N_NIMCALL(int, fflush)(void* stream__bCkp8dmVguW07m8JreNv8Q) {
	int result;
	result = (int)0;
	return result;
}
